"""created a comment model

Revision ID: e80430225ba7
Revises: 158598152ad6
Create Date: 2020-10-01 12:25:04.589264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80430225ba7'
down_revision = '158598152ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
